name: Generate Blog
on:
  push:
    branches:
      - master
    paths:
      - "_posts/**"
      - "_templates/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "\nDirectory contents:"
          ls -la
          echo "\nFull directory tree:"
          tree

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown feedgen jinja2 tree

      - name: Generate blog
        run: python blog_generator.py

      - name: Deploy to docs folder
        run: |
          mkdir -p docs/blog
          rm -rf docs/blog/*
          cp -r _site/* docs/

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add docs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-generate blog" && git push)
